repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff
        exclude: ^custom_components/victron_mqtt/_vendor/
        args:
          - --fix
      - id: ruff-format
        exclude: ^custom_components/victron_mqtt/_vendor/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --python-version=3.14 custom_components/victron_mqtt
        language: system
        pass_filenames: false
        types: [python]